# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default=b'')),
                ('ip_address', models.GenericIPAddressField()),
                ('read', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionRaw',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('suggestionbox.suggestion',),
        ),
    ]
