# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestionbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='deleted',
            new_name='blocked',
        ),
    ]
